{{ if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-dev
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://192.168.122.51:6443
  project: dev
  source:
    path: deploy/kube-prometheus-stack
    repoURL: git@github.com:haobinfei/gitops.git
    targetRevision: master
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - PrunePropagationPolicy=orphan
    - CreateNamespace=true
{{ end }}