apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external

resources:
- ./keycloak/service.yaml
- ./keycloak/ingress.yaml
- ./keycloak/endpoints.yaml
- ./grafana/ingress.yaml
- ./grafana/service.yaml
- ./grafana/endpoints.yaml
