apiVersion: v1
kind: Service
metadata:
  name: home-page  # Service 名称
spec:
  selector:
    app: home-page         # 必须与 Deployment 中 Pod 的标签一致
  ports:
    - protocol: TCP
      port: 80               # Service 暴露的端口（外部访问用）
      targetPort: 80         # 容器内监听的端口（即 Nginx 的 80 端口）
