apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- service-discovery.yaml
- ingress.yaml

# 通用标签和注解
commonLabels:
  app: keycloak
  managed-by: kustomize

commonAnnotations:
  version: v1.0.1
  description: "Keycloak Application"